# Generated by Django 2.1.5 on 2019-01-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Litigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_no', models.CharField(max_length=25, unique=True)),
                ('date', models.DateField()),
                ('respondents', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.CharField(max_length=256)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=2000)),
                ('reference_text', models.CharField(max_length=256)),
                ('litigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='litigations.Litigation')),
            ],
        ),
    ]
